export default [
  {
    id: 903,
    line: 'South Manchester',
    tLAREF: 'EDD',
    pIDREF: 'EDD-TPID03',
    stationLocation: 'East Didsbury',
    atcoCode: '9400ZZMAEDY1',
    direction: 'Incoming',
    dest0: 'Rochdale Town Centre',
    carriages0: 'Single',
    status0: 'Due',
    wait0: '1',
    dest1: 'Rochdale Town Centre',
    carriages1: 'Single',
    status1: 'Due',
    wait1: '14',
    dest2: 'Shaw and Crompton',
    carriages2: 'Single',
    status2: 'Due',
    wait2: '20',
    dest3: '',
    carriages3: '',
    status3: '',
    messageBoard:
      'On 6th & 7th July planned improvement works are taking place on the Bury line as part of the Trafford Park line project. For more information please visit www.tfgm.com or Tweet us at @MCRMetrolink',
    wait3: '',
    lastUpdated: '2019-07-05T16:00:44Z'
  },
  {
    id: 904,
    line: 'South Manchester',
    tLAREF: 'EDD',
    pIDREF: 'EDD-TPID04',
    stationLocation: 'East Didsbury',
    atcoCode: '9400ZZMAEDY1',
    direction: 'Incoming',
    dest0: 'Rochdale Town Centre',
    carriages0: 'Single',
    status0: 'Due',
    wait0: '1',
    dest1: 'Rochdale Town Centre',
    carriages1: 'Single',
    status1: 'Due',
    wait1: '14',
    dest2: 'Shaw and Crompton',
    carriages2: 'Single',
    status2: 'Due',
    wait2: '20',
    dest3: '',
    carriages3: '',
    status3: '',
    messageBoard:
      'On 6th & 7th July planned improvement works are taking place on the Bury line as part of the Trafford Park line project. For more information please visit www.tfgm.com or Tweet us at @MCRMetrolink',
    wait3: '',
    lastUpdated: '2019-07-05T16:00:44Z'
  },
  {
    id: 901,
    line: 'South Manchester',
    tLAREF: 'EDD',
    pIDREF: 'EDD-TPID01',
    stationLocation: 'East Didsbury',
    atcoCode: '9400ZZMAEDY2',
    direction: 'Incoming',
    dest0: 'Shaw and Crompton',
    carriages0: 'Single',
    status0: 'Due',
    wait0: '7',
    dest1: '',
    carriages1: '',
    status1: '',
    wait1: '',
    dest2: '',
    carriages2: '',
    status2: '',
    wait2: '',
    dest3: '',
    carriages3: '',
    status3: '',
    messageBoard:
      'On 6th & 7th July planned improvement works are taking place on the Bury line as part of the Trafford Park line project. For more information please visit www.tfgm.com or Tweet us at @MCRMetrolink',
    wait3: '',
    lastUpdated: '2019-07-05T16:00:44Z'
  },
  {
    id: 902,
    line: 'South Manchester',
    tLAREF: 'EDD',
    pIDREF: 'EDD-TPID02',
    stationLocation: 'East Didsbury',
    atcoCode: '9400ZZMAEDY2',
    direction: 'Incoming',
    dest0: 'Shaw and Crompton',
    carriages0: 'Single',
    status0: 'Due',
    wait0: '7',
    dest1: '',
    carriages1: '',
    status1: '',
    wait1: '',
    dest2: '',
    carriages2: '',
    status2: '',
    wait2: '',
    dest3: '',
    carriages3: '',
    status3: '',
    messageBoard:
      'On 6th & 7th July planned improvement works are taking place on the Bury line as part of the Trafford Park line project. For more information please visit www.tfgm.com or Tweet us at @MCRMetrolink',
    wait3: '',
    lastUpdated: '2019-07-05T16:00:44Z'
  }
];
