export default [
  {
    id: 749,
    line: 'Altrincham',
    tLAREF: 'TMP',
    pIDREF: 'TMP-TPTD01',
    stationLocation: 'Timperley',
    atcoCode: '9400ZZMATIM2',
    direction: 'Incoming',
    dest0: 'Old Trafford',
    carriages0: 'Double',
    status0: 'Arrived',
    wait0: '0',
    dest1: 'Piccadilly',
    carriages1: 'Single',
    status1: 'Due',
    wait1: '5',
    dest2: 'Piccadilly',
    carriages2: 'Single',
    status2: 'Due',
    wait2: '21',
    dest3: 'Piccadilly',
    carriages3: 'Single',
    status3: 'Departing',
    messageBoard:
      'On 21st & 22nd September planned engineering works are taking place in the Cornbrook area affecting some tram services. For more information please visit www.TfGM.com or tweet us @MCRMetrolink',
    wait3: '0',
    lastUpdated: '2019-09-16T20:19:38Z'
  },
  {
    id: 750,
    line: 'Altrincham',
    tLAREF: 'TMP',
    pIDREF: 'TMP-TPTD02',
    stationLocation: 'Timperley',
    atcoCode: '9400ZZMATIM1',
    direction: 'Outgoing',
    dest0: 'Altrincham',
    carriages0: 'Single',
    status0: 'Departing',
    wait0: '0',
    dest1: 'Altrincham',
    carriages1: 'Double',
    status1: 'Due',
    wait1: '14',
    dest2: 'Altrincham',
    carriages2: 'Single',
    status2: 'Due',
    wait2: '25',
    dest3: 'Altrincham',
    carriages3: 'Single',
    status3: 'Arrived',
    messageBoard:
      'On 21st & 22nd September planned engineering works are taking place in the Cornbrook area affecting some tram services. For more information please visit www.TfGM.com or tweet us @MCRMetrolink',
    wait3: '0',
    lastUpdated: '2019-09-16T20:19:38Z'
  }
];
